drop table if exists district cascade;
drop table if exists state cascade;

create table district (
   id integer generated by default as identity (start with 1),
    name varchar(255) not null,
    state_id integer not null,
    primary key (id)
);

create table state (
   id integer generated by default as identity (start with 1),
    capital varchar(255) not null,
    name varchar(255) not null,
    porpulation integer not null,
    region varchar(255) not null,
    type varchar(255) not null,
    primary key (id)
);

alter table state 
   add constraint UK_2g0hi7w44i4sjkffh61pusaav unique (name);

alter table district 
   add constraint FK9q0dmy9dgad2d0ewohftj87cn 
   foreign key (state_id) 
   references state;