create table category (
	id int generated by default as IDENTITY(start with 1) primary key,
	name varchar(20) unique not null
);

create table product (
	id int generated by default as IDENTITY(start with 1) primary key,
	category_id int not null,
	name varchar(40) not null,
	price int,
	foreign key (category_id) references category(id)
);