drop table if exists State cascade;
create table State (
   id integer generated by default as identity (start with 1),
    capital varchar(255),
    name varchar(255) not null,
    porpulation integer not null,
    region varchar(255),
    type varchar(255) not null,
    primary key (id)
);
alter table State 
   add constraint UK_lsi0h01bmubfv1uhfe8wyyaks unique (name);